name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or your default branch

env:
  REGION: us-west1  # Replace with your desired region
  SERVICE_NAME: process-emails  # Replace with your desired service name

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}  # Workload Identity Federation provider
          service_account: ${{ secrets.SERVICE_ACCOUNT }}  # Service account email

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: |-
          docker build -t gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          env_vars: |
            USER_EMAIL=${{ secrets.USER_EMAIL }}
            LABEL_NAME=${{ secrets.LABEL_NAME }}
          secrets: |
            GMAIL_CREDENTIALS=gmail_credentials:latest
            GMAIL_TOKEN=gmail_token:latest 