name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # or your default branch

env:
  REGION: us-west1  # Replace with your desired region
  SERVICE_NAME: process-emails  # Replace with your desired service name
  REGISTRY: us-west1-docker.pkg.dev  # Artifact Registry location

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push
        run: gcloud auth configure-docker ${{ env.REGISTRY }}

      - name: Create Artifact Registry repository
        run: |
          gcloud artifacts repositories create ${{ env.SERVICE_NAME }} \
            --repository-format=docker \
            --location=${{ env.REGION }} \
            --quiet || true

      - name: Build and Push Container
        run: |-
          docker build -t ${{ env.REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}/app:${{ github.sha }} process_emails/
          docker push ${{ env.REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}/app:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGISTRY }}/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}/app:${{ github.sha }}
          env_vars: |
            USER_EMAIL=${{ secrets.USER_EMAIL }}
            LABEL_NAME=${{ secrets.LABEL_NAME }}
          secrets: |
            GMAIL_CREDENTIALS=gmail_credentials:latest
            GMAIL_TOKEN=gmail_token:latest 